apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
  # The label is used for matching the exact claim
  labels:
    usage: mysql-storage
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: storage-secret
    shareName: mysqlshare
    readOnly: false