apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-storage
  # The label is used for matching the exact claim
  labels:
    usage: wordpress-storage
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: storage-secret
    shareName: blogfileshare
    readOnly: false