apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/ghost-pv-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv-2
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/ghost-pv-2
