apiVersion: v1
kind: Service
metadata:
  name: aspnetcoreapp
  labels:
    app: aspnetcoreapp
spec:
  ports:
    - port: 80
  selector:
    app: aspnetcoreapp
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kolexinfos-deployment
spec:
  selector:
    matchLabels:
      app: aspnetcoreapp
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: aspnetcoreapp
        tier: frontend
    spec:
      containers:
      - name: aspnetcoreapp
        image: kolexinfos/aspnetcoreapp:latest
        ports:
         - name: aspnetcoreapp
           containerPort: 80
           protocol: TCP
        